export const CORE_FINAL_BOUNDARY_IDENTITIES = [
  ["src/surface/adapter.ts", "surfaceExternalFallback"],
  ["src/surface/adapter.ts", "surfaceExternalFallback.<callback>"],
  ["src/surface/discord/discord-embed-text.ts", "normalizeDiscordEmbeds"],
  ["src/surface/discord/discord-message-meta.ts", "normalizeFlagsNumber"],
  ["src/surface/discord/discord-resource-origin.ts", "getVisibleDiscordResourceAttachments"],
  ["src/surface/discord/discord-request-router/common.ts", "withDefaultToolsConfig"],
  ["src/surface/discord/discord-adapter.ts", "discordNotFoundCode"],
  ["src/surface/discord/discord-adapter.ts", "classifyDiscordSurfaceError"],
  [
    "src/surface/discord/discord-adapter.ts",
    "DiscordAdapter.connect.on.<callback@2>.catch.<callback@1>",
  ],
  [
    "src/surface/discord/discord-adapter.ts",
    "DiscordAdapter.registerSlashCommands.catch.<callback@1>",
  ],
  ["src/surface/bridge/adapter-event-projection.ts", "toBusEvtAdapterMessageCreated"],
  ["src/surface/bridge/adapter-event-projection.ts", "toBusEvtAdapterMessageUpdated"],
  ["src/surface/bridge/adapter-event-projection.ts", "toBusEvtAdapterMessageDeleted"],
  ["src/surface/bridge/adapter-event-projection.ts", "toBusEvtAdapterReactionAdded"],
  ["src/surface/bridge/adapter-event-projection.ts", "toBusEvtAdapterReactionRemoved"],
  ["src/surface/discord/discord-command-projection.ts", "toBusDiscordCommandInvokedData"],
  ["src/surface/bridge/surface-metadata.ts", "extractLeadingTextContent"],
  ["src/github/github-app.ts", "decodeGithubAppSecret"],
  ["src/github/github-user-token.ts", "decodeGithubUserTokenSecret"],
  ["src/github/github-auth.ts", "fetchViewerLoginFromGithub"],
  ["src/github/github-api.ts", "githubFetchJson"],
  ["src/github/github-api.ts", "captureGithubAppResponse"],
  ["src/surface/github/github-adapter.ts", "classifyGithubSurfaceError"],
  ["src/surface/github/github-adapter.ts", "toGithubMessage"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "normalizeOptionalNonEmptyString"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "normalizeSessionMode"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "normalizeStringArray"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "normalizeBooleanTrue"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "normalizeOptionalString"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "normalizeSubagentProfile"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "normalizeOptionalFiniteNumber"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "normalizeModelReasoningEffort"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "parseWorkflowRequestHintFromRaw"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "parseRouterRaw"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "parseRouterSessionModeFromRaw"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "parseSessionConfigIdFromRaw"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "parseParentChannelIdFromRaw"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "parseGuildIdFromRaw"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "parseRequestModelOverrideFromRaw"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "parseBufferedForActiveRequestIdFromRaw"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "getChainMessageIdsFromRaw"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "getParticipantUserIdsFromRaw"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "parseSubagentMetaFromRaw"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "parseCustomCommandFromRaw"],
  ["src/surface/bridge/subscribe-from-bus.ts", "bridgeBusToAdapter.subscribeTopic.<callback@3>@1"],
  ["src/surface/bridge/publish-to-bus.ts", "bridgeAdapterToBus.subscribe.<callback@1>"],
  ["src/surface/bridge/subscribe-from-bus.ts", "bridgeBusToAdapter.startRelay.pushOutputPart"],
  ["src/surface/bridge/subscribe-from-bus.ts", "bridgeBusToAdapter.startRelay.finishOutput"],
  ["src/surface/discord/discord-raw-normalizer.ts", "normalizeReference"],
  ["src/surface/discord/discord-raw-normalizer.ts", "normalizeDiscordRaw"],
  ["src/surface/discord/discord-raw-normalizer.ts", "normalizeDiscordRaw.parseRecord"],
  [
    "src/surface/discord/discord-raw-normalizer.ts",
    "normalizeDiscordRaw.normalizeDiscordAttachment",
  ],
  [
    "src/surface/discord/discord-raw-normalizer.ts",
    "normalizeDiscordRaw.normalizeDiscordAttachments",
  ],
  [
    "src/surface/discord/discord-raw-normalizer.ts",
    "normalizeDiscordRaw.firstForwardSnapshotMessage",
  ],
  ["src/surface/discord/discord-surface-display-text.ts", "getDiscordSurfaceTextFromRaw"],
  ["src/surface/discord/discord-surface-display-text.ts", "getDiscordSurfaceDisplayText"],
  [
    "src/surface/store/discord-search-store.ts",
    "DiscordSearchStore.upsertMessages.transaction.<callback@1>",
  ],
  ["src/conversation/thread-service.ts", "readPromptContextFile"],
  ["src/conversation/thread-service.ts", "parseSummaryJson"],
  ["src/conversation/thread-service.ts", "parseQueryAboutnessJson"],
  ["src/conversation/thread-service.ts", "parseAutoInjectQueryPlanJson"],
  [
    "src/conversation/thread-service.ts",
    "ConversationThreadService.runSummarization.processThread",
  ],
  ["src/conversation/thread-service.ts", "ConversationThreadService.summarizeWithParseRetries"],
  ["src/conversation/thread-service.ts", "ConversationThreadService.captureQueryAboutness"],
  ["src/conversation/thread-service.ts", "ConversationThreadService.searchHits"],
  ["src/workflow/workflow-domain.ts", "normalizeWorkflowResourcePolicyResult"],
  ["src/workflow/workflow-domain.ts", "normalizeWorkflowResourcePolicy"],
  ["src/workflow/workflow-operation-policy.ts", "resolveWorkflowAgentOperationInputResult"],
  ["src/workflow/workflow-definition.ts", "assertStaticHostCallArguments.assertStaticObject"],
  ["src/workflow/workflow-definition.ts", "extractStaticMetadata"],
  ["src/workflow/workflow-definition.ts", "validateWorkflowArgsUnchecked"],
  ["src/workflow/workflow-definition.ts", "validateWorkflowSourceUnchecked"],
  [
    "src/workflow/durable-workflow-store.ts",
    "DurableWorkflowStore.listMigrations.map.<callback@1>",
  ],
  ["src/workflow/durable-workflow-store.ts", "DurableWorkflowStore.getLiveParentDeliverySnapshot"],
  ["src/workflow/durable-workflow-store.ts", "DurableWorkflowStore.getLiveParentDeliveryState"],
  [
    "src/workflow/durable-workflow-store.ts",
    "DurableWorkflowStore.matchesWorkflowRequestPolicyIdentity",
  ],
  [
    "src/workflow/durable-workflow-store.ts",
    "DurableWorkflowStore.summarizeMeaningfulOperations.map.<callback@1>",
  ],
  [
    "src/workflow/workflow-progress-projector.ts",
    "WorkflowProgressProjector.requestProjection.setTimeout.<callback@1>.catch.<callback@1>",
  ],
  [
    "src/workflow/workflow-progress-projector.ts",
    "WorkflowProgressProjector.reconcile.catch.<callback@1>",
  ],
  ["src/mcp/catalog-identity.ts", "parseCatalogToolStableId"],
  ["src/mcp/config.ts", "parseMcpConfigDocument"],
  ["src/mcp/modern-result-validation.ts", "decodeJsonRpcPayload"],
  ["src/mcp/modern-result-validation.ts", "isValidModernDiscoverResult"],
  ["src/mcp/modern-result-validation.ts", "isLegacyDiscoverResult"],
  ["src/mcp/modern-result-validation.ts", "isValidModernCacheableCompleteResult"],
  ["src/mcp/modern-result-validation.ts", "allowsLegacyFallback"],
  ["src/mcp/modern-result-validation.ts", "retainTransportPanic"],
  ["src/mcp/modern-result-validation.ts", "preserveTransportPanic"],
  ["src/mcp/modern-result-validation.ts", "signalTransportCancellation"],
  ["src/mcp/registry.ts", "McpRegistry.listAllTools"],
  ["src/mcp/registry.ts", "McpRegistry.wrapToolExecution.execute.<callback>"],
  ["src/mcp/registry.ts", "McpRegistry.wrapToolExecution.execute"],
  ["src/mcp/credential-file.ts", "resolveMcpOAuthCredentialPathResult"],
  ["src/mcp/credential-file.ts", "readMcpOAuthCredentialFileResult"],
  ["src/mcp/credential-file.ts", "writeMcpOAuthCredentialFileAtomicResult"],
  ["src/tools/apply-patch/local-apply-patch-tool.ts", "decodeOptionalToolContext"],
  ["src/tools/apply-patch/local-apply-patch-tool.ts", "localApplyPatchTool.execute"],
  ["src/tools/batch-error-message.ts", "decodeBatchParameters"],
  ["src/tools/tool-env.ts", "decodeToolEnvEntry"],
  ["src/tools/tool-env.ts", "parseToolEnvResult"],
  ["src/tools/tool-env.ts", "parseToolEnv"],
  ["src/tools/tool-env.ts", "loadToolEnv"],
  ["src/tools/restricted-bash.ts", "captureRestrictedHostPromise.then.<callback@2>"],
  ["src/tools/restricted-bash.ts", "RestrictedReadFs.assertReadable"],
  ["src/tools/restricted-bash.ts", "RestrictedReadFs.assertWritable"],
  ["src/tools/restricted-bash.ts", "RestrictedReadFs.exists"],
  ["src/tools/restricted-bash.ts", "decodeNestedToolInput"],
  ["src/tools/restricted-bash.ts", "formatToolOutput"],
  ["src/tools/restricted-bash.ts", "fetchToolHelp"],
  ["src/tools/restricted-bash.ts", "buildNestedToolInput"],
  ["src/tools/restricted-bash.ts", "createToolsCommand.defineCommand.<callback@2>.runToolsCommand"],
  ["src/tools/subagent.ts", "decodeRequestContext"],
  ["src/tools/subagent.ts", "subagentTools.execute"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "getStringField"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "getNumberField"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "getBooleanField"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "formatToolLogPreview"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "toSerializablePreview"],
  ["src/surface/bridge/bus-agent-runner/stats.ts", "getToolDefsText.map.<callback@1>"],
  ["src/tools/tool-args-display.ts", "safeValidateSync"],
  ["src/tools/tool-args-display.ts", "safeValidateSync.try"],
  ["src/tools/tool-args-display.ts", "getPathArg"],
  ["src/tools/tool-args-display.ts", "getGlobArgs"],
  ["src/tools/tool-args-display.ts", "getGrepArgs"],
  ["src/tools/tool-args-display.ts", "getFuzzySearchArgs"],
  ["src/tools/tool-args-display.ts", "formatReadFileToolArgs"],
  ["src/tools/tool-args-display.ts", "formatBashToolArgs"],
  ["src/tools/tool-args-display.ts", "formatGlobToolArgs"],
  ["src/tools/tool-args-display.ts", "formatGrepToolArgs"],
  ["src/tools/tool-args-display.ts", "formatFuzzySearchToolArgs"],
  ["src/tools/tool-args-display.ts", "formatSubagentDelegateToolArgs"],
  ["src/tools/tool-args-display.ts", "formatApplyPatchToolArgs"],
  ["src/tools/tool-args-display.ts", "formatEditFileToolArgs"],
  ["src/tools/tool-args-display.ts", "formatBatchToolArgs"],
  ["src/tools/tool-args-display.ts", "formatToolArgsForDisplay"],
  ["src/tools/tool-args-display.ts", "formatToolArgsForDisplayWithSpecs"],
  ["src/plugins/builtin/local-tools.ts", "decodeCoreToolRequestMetadata"],
  ["src/plugins/builtin/local-tools.ts", "getEditFileTool"],
  ...Array.from(
    { length: 9 },
    (_, index) => ["src/plugins/builtin/local-tools.ts", `summarizeFailure@${index + 1}`] as const,
  ),
  ["src/plugins/builtin/local-tools.ts", "editTargets@1"],
  ["src/plugins/builtin/local-tools.ts", "editTargets@2"],
  ["src/workflow/workflow-definition-store.ts", "WorkflowDefinitionStore.definitionPath"],
  ["src/workflow/workflow-definition-store.ts", "WorkflowDefinitionStore.getUnchecked"],
  ["src/workflow/workflow-definition-store.ts", "WorkflowDefinitionStore.saveUnchecked"],
  ["src/workflow/workflow-definition-store.ts", "WorkflowDefinitionStore.listUnchecked"],
  ["src/transcript/heartbeat-handoff.ts", "extractHeartbeatSurfaceSendHandoffs"],
  ["src/transcript/heartbeat-handoff.ts", "projectHeartbeatToolInput"],
  ["src/mcp/catalog.ts", "catalogCandidateExecutable"],
  ["src/mcp/catalog.ts", "createPortableToolSearch"],
  ["src/plugins/manager.ts", "resolveOpaquePluginConfig"],
  ["src/plugins/manager.ts", "assignOpaqueTool"],
  ["src/plugins/manager.ts", "readOpaqueTool"],
  [
    "src/conversation/thread-materializer-worker-protocol.ts",
    "decodeThreadMaterializerWorkerRequest",
  ],
  [
    "src/conversation/thread-materializer-worker-protocol.ts",
    "decodeThreadMaterializerWorkerResponse",
  ],
  ["src/conversation/thread-materializer-worker-isolate.ts", "addEventListener.<callback@2>"],
  [
    "src/conversation/thread-materializer-worker.ts",
    "startConversationThreadMaterializer.configureWorker.setMessageHandler.<callback@1>",
  ],
  ["src/conversation/thread-summarization-worker.ts", "addEventListener.<callback@2>"],
  [
    "src/conversation/thread-worker.ts",
    "startConversationThreadSummarizationWorker.onMessage.<callback@1>",
  ],
  ["src/github/webhook/github-webhook-server.ts", "decodeGithubWebhookEvent"],
  ["src/surface/bridge/request-composition/normalization.ts", "extractAssistantTextFromContent"],
  ["src/surface/bridge/request-composition/reply-chain.ts", "getForwardSnapshotTextFromRaw"],
  ["src/surface/bridge/request-composition/reply-chain.ts", "extractDiscordAttachmentsFromRaw"],
  ["src/surface/bridge/request-composition/reply-chain.ts", "getReferenceFromRaw"],
  ["src/surface/bridge/request-composition/reply-chain.ts", "toReplyChainMessage"],
  ["src/surface/bridge/request-composition/reply-chain.ts", "findEarliestReplyAnchor"],
  [
    "src/surface/bridge/request-composition/reply-chain.ts",
    "mergeChainByDiscordWindow.map.<callback@1>",
  ],
  ["src/surface/bridge/request-composition.ts", "shouldIncludeInModelContext"],
  ["src/surface/bridge/request-composition.ts", "getSurfaceMessageContextText"],
  ["src/surface/bridge/request-composition.ts", "shouldApplyContinueDirectiveToSurfaceMessage"],
  ["src/surface/bridge/request-composition.ts", "composeRequestMessages.filter.<callback@1>"],
  ["src/surface/bridge/request-composition.ts", "composeSingleMessageWithLineage"],
  ["src/surface/discord/discord-request-router/publish.ts", "publishBusRequest"],
  [
    "src/surface/discord/discord-request-router.ts",
    "startDiscordRequestRouter.subscribeTopic.<callback@3>@3.captureRouterRouting.<callback@2>@2",
  ],
  ["src/surface/discord/discord-request-router.ts", "startDiscordRequestRouter.flushDebounce"],
  [
    "src/workflow/workflow-live-parent-bridge.ts",
    "WorkflowLiveParentBridge.enableOrphanHandling.setTimeout.<callback@1>.catch.<callback@1>",
  ],
  ["src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts", "readProviderOrder"],
  [
    "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
    "withStableAnthropicUpstreamOrder",
  ],
  ["src/surface/bridge/bus-agent-runner/error-display.ts", "readNonEmptyString"],
  ["src/surface/bridge/bus-agent-runner/provider-options.ts", "mergeProviderOptions"],
  ["src/surface/bridge/bus-agent-runner/text-units.ts", "userContentText"],
  ["src/surface/bridge/bus-agent-runner/stats.ts", "estimateInputCompositionChars"],
  ["src/surface/bridge/bus-agent-runner/stats.ts", "systemPromptToText"],
  ["src/surface/bridge/bus-agent-runner/stats.ts", "buildInputCompositionLine"],
  ["src/surface/bridge/bus-agent-runner/core-named-continuation.ts", "semanticFingerprint"],
  ["src/surface/bridge/bus-agent-runner.ts", "estimateTokensFromValue"],
  ["src/surface/bridge/bus-agent-runner.ts", "projectBusAgentRunnerError"],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.handleCmdRequestMessage.<callback>",
  ],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.reportAgentActivityError",
  ],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.decideIdleRecovery",
  ],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>@2.turnErrorHandler",
  ],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>@2.reportServerCompactionError",
  ],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>@2.onUnknownCapability",
  ],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>@2.onCompactionEnd",
  ],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>@2.subscribe.<callback@1>",
  ],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>@2.subscribe.<callback@1>.publishAuxiliaryOutput.<callback@2>@4",
  ],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>@2.subscribe.<callback@1>.publishAuxiliaryOutput.<callback@2>@5",
  ],
  ["src/surface/bridge/bus-agent-runner.ts", "getBatchOkFromResult"],
  ["src/surface/bridge/bus-agent-runner.ts", "getSubagentOkFromResult"],
  ["src/surface/bridge/bus-agent-runner.ts", "decodeDeferredSubagentAcceptedResult"],
  ["src/surface/bridge/bus-agent-runner.ts", "collectAutoInjectedThreadIds"],
  ["src/surface/bridge/bus-agent-runner.ts", "validateCorePrimaryLineageAtRunnerIntake"],
  ["src/surface/bridge/bus-agent-runner.ts", "appendAutoInjectedThreadSearchLineage"],
  ["src/surface/bridge/bus-agent-runner.ts", "collectBufferedPromptEntriesForActiveRequest"],
  ["src/surface/bridge/bus-agent-runner.ts", "modelChangingRequestId"],
  ["src/surface/bridge/bus-agent-runner.ts", "applyToRunningAgent"],
  ["src/workflow/workflow-source-compiler.ts", "parseWorkflowCallSiteManifestUnchecked"],
  ["src/workflow/workflow-sandbox.ts", "decodeWorkflowSandboxOutputLine"],
  ["src/workflow/workflow-sandbox.ts", "startWorkflowSandbox.executionResult.<callback>"],
  ["src/workflow/workflow-sandbox.ts", "startWorkflowSandbox.result.<callback>"],
  [
    "src/workflow/workflow-sandbox.ts",
    "startWorkflowSandbox.executionResult.<callback>.stderrPromise.<callback>",
  ],
  ["src/workflow/workflow-engine.ts", "decodeWorkflowCallInput"],
  ["src/workflow/workflow-waits.ts", "replyToMessageId"],
  [
    "src/runtime/create-core-runtime.ts",
    "createCoreRuntime.startCoreConfigWatcher.on.<callback@2>",
  ],
  ["src/runtime/create-core-runtime.ts", "createCoreRuntime.start.catch.<callback@1>"],
  ["src/runtime/create-core-runtime.ts", "normalizeRouterDoneDefect"],
  ["src/tools/attachment.ts", "normalizeAttachmentAddFilesInput"],
  ["src/tools/attachment.ts", "attachmentTools.execute@2"],
  ["src/surface/bridge/bus-agent-runner/core-named-continuation.ts", "hashCoreNamedExecutionScope"],
  [
    "src/workflow/durable-workflow-store.ts",
    "DurableWorkflowStore.recordLiveParentCompletionMaterializationFailure.runWorkflowTransactionForStoreHost.<callback@3>",
  ],
  [
    "src/workflow/durable-workflow-store.ts",
    "DurableWorkflowStore.commitSurfaceBindingWithActionRevocation",
  ],
  ["src/surface/runtime-descriptor.ts", "workflowProgressOperationFailure"],
  [
    "src/workflow/workflow-progress-projector.ts",
    "WorkflowProgressProjector.writeRetryableFailure",
  ],
  [
    "src/workflow/workflow-progress-projector.ts",
    "WorkflowProgressProjector.writePermanentFailure",
  ],
  ["src/mcp/registry.ts", "safeErrorText"],
  ["src/mcp/registry.ts", "McpRegistry.failureStatus"],
  ["src/tools/batch-error-message.ts", "formatBatchPreflightMissingFieldError"],
  ["src/tools/batch-error-message.ts", "formatBatchChildValidationError"],
  ["src/tools/restricted-bash.ts", "restrictedHostErrorCode"],
  ["src/tools/restricted-bash.ts", "readHttpErrorMessage"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "defaultErrorFromResult"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "summarizeBashFailure"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "summarizeReadOrEditFailure"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "summarizeSearchFailure"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "summarizeApplyPatchFailure"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "summarizeBatchFailure"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "summarizeSubagentFailure"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "summarizeToolFailure"],
  ["src/surface/bridge/bus-agent-runner/formatting.ts", "debugJsonStringify"],
  ["src/surface/bridge/bus-agent-runner/error-display.ts", "formatErrorLabel"],
  ["src/surface/bridge/bus-agent-runner/error-display.ts", "extractReadableErrorMessage"],
  ["src/surface/bridge/bus-agent-runner/error-display.ts", "formatUnknownErrorForDisplay"],
  ["src/workflow/workflow-sandbox.ts", "errorFrom"],
  ["src/workflow/workflow-engine.ts", "boundedError"],
  ["src/runtime/main.ts", "projectProcessFailure"],
  ["src/tools/tool-env.ts", "isMissingToolEnvFile"],
  ["src/mcp/registry.ts", "isOptionalHttpInboundSseError"],
  ["src/mcp/config-file.ts", "McpConfigError.constructor"],
  ["src/mcp/oauth-provider.ts", "McpOAuthProviderError.constructor"],
  ["src/surface/bridge/bus-agent-runner.ts", "signalBusAgentRunnerHostFailure"],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>.reportAutoInjectedThreadSearchError",
  ],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>.reportServerCompactionError",
  ],
  [
    "src/surface/bridge/bus-agent-runner.ts",
    "startBusAgentRunner.drainSessionQueue.captureBusAgentRunnerOperation.<callback@2>.turnErrorHandler",
  ],
  [
    "src/surface/bridge/bus-agent-runner/core-named-continuation.ts",
    "createCoreNamedClaudeRuntime.diagnostic",
  ],
  [
    "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
    "createCorePrimaryClaudeRuntime.diagnostic",
  ],
  ["src/surface/discord/discord-request-router/publish.ts", "publishSingleMessagePrompt"],
  ["src/surface/bridge/request-composition.ts", "applyUserTextTransformToReplyChainMessage"],
  ["src/surface/bridge/request-composition.ts", "composeSelectedDiscordChain.map.<callback@1>"],
  ["src/surface/bridge/request-composition.ts", "stripContinueDirectiveFromReplyChainMessage"],
  ["src/tool-server/create-tool-server.ts", "createToolServer.logPluginError"],
  ["src/tool-server/create-tool-server.ts", "createToolServer.post.<callback@2>"],
  ["src/tool-server/create-tool-server.ts", "createToolServer.post.<callback@2>.then.<callback@1>"],
  ["src/tool-server/create-tool-server.ts", "toolServerTaggedErrorLogProjection"],
  ["src/tool-server/tools/surface.ts", "extractAttachmentMetaFromList"],
  ["src/tools/bash-impl.ts", "cleanupBashSpills"],
  ["src/tools/bash-impl.ts", "executeBash.runExecution"],
  ["src/tools/bash-output-sanitizer.ts", "readSanitizedStreamTextCappedResult"],
  ["src/tools/bash-output-sanitizer.ts", "readSanitizedStreamTextCappedResult.failOverflow"],
  [
    "src/tools/bash-output-sanitizer.ts",
    "readSanitizedStreamTextCappedResult.recordCleanupAttempt",
  ],
  ["src/tools/bash-output-sanitizer.ts", "readSanitizedStreamTextCappedResult.writeOverflowChunk"],
  [
    "src/transcript/heartbeat-handoff.ts",
    "compactHeartbeatHandoffMessages.map.<callback@1>.map.<callback@1>",
  ],
  [
    "src/conversation/thread-embedding.ts",
    "createConversationThreadEmbeddingAdapterResolver.resolve.catch",
  ],
  ["src/conversation/thread-materializer-worker-isolate.ts", "runRequest.catch"],
  [
    "src/conversation/thread-materializer-worker.ts",
    "startConversationThreadMaterializer.postRequest.catch",
  ],
  ["src/conversation/thread-materializer.ts", "createThreadMaterializer.drain.catch"],
  ["src/conversation/thread-materializer.ts", "createThreadMaterializer.reportError.catch"],
  ["src/conversation/thread-service.ts", "ConversationThreadService.tryEmbedThread.catch"],
  ["src/conversation/thread-service.ts", "defaultSummarizer.catch"],
  ["src/conversation/thread-store.ts", "ConversationThreadStore.attachSurfaceDb.catch"],
  ["src/conversation/thread-store.ts", "ConversationThreadStore.hasRequiredSurfaceTables.catch"],
  ["src/conversation/thread-store.ts", "ConversationThreadStore.loadVectorExtension.catch"],
  ["src/runtime/error-format.ts", "projectRuntimeError"],
  ["src/runtime/error-format.ts", "safeRuntimeErrorText"],
  [
    "src/shared/agent-output-activity.ts",
    "createAgentOutputActivityPublisher.<callback>.catch.<callback@1>",
  ],
  ["src/tools/bash-impl.ts", "formatBashStreamFailureForLog"],
  ["src/transcript/heartbeat-handoff.ts", "safeStringify.catch"],
  ["src/workflow/workflow-sandbox.ts", "startWorkflowSandbox.then.<callback@2>"],
  ["src/ssh/remote-js/remote-runner-utils.ts", "opaqueErrorCause"],
] as const;
export const CORE_FINAL_CAPABILITY_IDENTITIES = [
  ["src/surface/adapter.ts", "hasCacheBurstProvider"],
  ["src/surface/adapter.ts", "hasRequestReadScopeProvider"],
  ["src/surface/discord/discord-adapter.ts", "classifyDiscordSurfaceNotFound"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "isModelReasoningEffort"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "requestRawReferencesMessage"],
  ["src/surface/bridge/bus-agent-runner/raw.ts", "isSubagentProfile"],
  ["src/mcp/registry.ts", "isOptionalHttpInboundSseError"],
  ["src/tools/tool-env.ts", "isMissingToolEnvFile"],
  ["src/plugins/builtin/local-tools.ts", "isDelegateHandler"],
  ["src/plugins/builtin/local-tools.ts", "isAgentActivityHandler"],
  ["src/surface/bridge/request-composition/reply-chain.ts", "hasReplyTargetInRaw"],
  ["src/surface/bridge/bus-agent-runner.ts", "hasDeferredSubagentWorkflowCall"],
  ["src/surface/bridge/bus-agent-runner.ts", "isWorkflowAgentRecoveryEntry"],
  ["src/surface/bridge/bus-agent-runner.ts", "isCancelControlEntry"],
] as const;
export const CORE_FINAL_REVIEWED_OPAQUE_IDENTITIES = [
  [
    "src/workflow/workflow-live-parent-bridge.ts",
    "WorkflowLiveParentBridge.registerParent.catch.<callback@1>",
  ],
  ["src/conversation/thread-worker.ts", "rethrowConversationThreadWorkerPanic"],
  ["src/github/github-api.ts", "captureGithubResponseText.captureGithubApiExternal.<callback@2>"],
  ["src/github/github-api.ts", "getGithubAppSlugOrNull.captureGithubApiExternal.<callback@2>@1"],
  ["src/github/github-api.ts", "getGithubAppSlugOrNull.captureGithubApiExternal.<callback@2>@2"],
  ["src/github/github-app.ts", "chmod0600.captureGithubAppFs.<callback@2>"],
  ["src/github/github-app.ts", "readGithubAppSecretResult.captureGithubAppFs.<callback@2>"],
  ["src/github/github-app.ts", "clearGithubAppSecret.captureGithubAppFs.<callback@2>"],
  ["src/github/github-app.ts", "readGithubAppPrivateKeyPemResult.captureGithubAppFs.<callback@2>"],
  ["src/github/github-user-token.ts", "chmod0600.captureGithubUserTokenFs.<callback@2>"],
  [
    "src/github/github-user-token.ts",
    "readGithubUserTokenSecretResult.captureGithubUserTokenFs.<callback@2>",
  ],
  [
    "src/github/github-user-token.ts",
    "clearGithubUserTokenSecret.captureGithubUserTokenFs.<callback@2>",
  ],
  ["src/surface/adapter.ts", "preserveSurfacePanic"],
  ["src/surface/bridge/subscribe-from-bus.ts", "rethrowBusToAdapterPanic"],
  ["src/surface/bridge/bus-agent-runner.ts", "rethrowBusAgentRunnerPanic"],
  ["src/mcp/credential-file.ts", "credentialError"],
  ["src/mcp/oauth-provider.ts", "oauthProviderError"],
  ["src/runtime/main.ts", "handleUnhandledRejection"],
  ["src/surface/bridge/bus-agent-runner/tool-failure-logging.ts", "ToolFailureSummarizer.<call>"],
] as const;

export const CORE_FINAL_CAPTURE_IDENTITIES = [
  ["src/tools/apply-patch/apply-patch-core.ts", "captureApplyPatchOperation.catch"],
  ["src/tools/bash-output-sanitizer.ts", "captureBashOutputOperation.catch"],
  ["src/tools/bash-output-sanitizer.ts", "captureBashOutputPromise.catch"],
  ["src/tools/tool-env.ts", "captureToolEnvFileOperation.catch"],
  ["src/tools/tool-env.ts", "decodeToolEnvJson.catch"],
  ["src/tools/bash-impl.ts", "overflowStreamBytes.catch"],
  ["src/tools/bash-impl.ts", "readOverflowTail.catch"],
  ["src/tools/bash-impl.ts", "persistTruncatedOutput.catch"],
  ["src/tools/bash-impl.ts", "executeBash.killProcessGroupBestEffort.catch"],
  ["src/tools/restricted-bash.ts", "captureRestrictedBashOperation.catch"],
  ["src/tools/restricted-bash.ts", "captureRestrictedBashSync.catch"],
  ["src/tools/restricted-bash.ts", "decodeRestrictedJson.catch"],
  ["src/tools/subagent.ts", "captureSubagentOperation.catch"],
  ["src/runtime/process-handlers.ts", "createProcessHandlers.superviseFatal.catch"],
  ["src/runtime/main.ts", "catch"],
  ["src/runtime/main.ts", "handleProcessSignal.catch"],
  ["src/tools/attachment.ts", "captureAttachmentOperation.catch"],
  [
    "src/mcp/registry.ts",
    "McpRegistry.initializeCandidate.withDeadline.<callback@2>.onUncaughtError",
  ],
  ["src/conversation/thread-materializer.ts", "mapListChannelIdsError"],
] as const;
