export type PreciseExceptionIdentity = readonly [
  module: string,
  exportName: string,
  mode: "signal",
];

export const CORE_REVIEWED_PANIC_IDENTITIES = [
  ["src/surface/adapter.ts", "preserveSurfacePanic"],
  ["src/mcp/modern-result-validation.ts", "preserveTransportPanic"],
] as const;

export const CORE_FATAL_SIGNAL_IDENTITIES = [
  [
    "src/surface/discord/discord-adapter.ts",
    "DiscordAdapter.reportDetachedPanic.queueMicrotask.<callback@1>",
  ],
] as const;

export const PRECISE_EXCEPTION_IDENTITIES = {
  "apps/acp-controller": [
    ["external-adapters.ts", "signalAcpDefect", "signal"],
    [
      "acp-harness-client.ts",
      "AcpHarnessClient.connect.captureExternal.<callback@2>@2.start",
      "signal",
    ],
    [
      "acp-harness-client.ts",
      "AcpHarnessClient.connect.captureExternal.<callback@2>@2.start.captureFailure.<callback>",
      "signal",
    ],
  ],
  "apps/core": [
    ["src/agent/claude-composition.ts", "canonicalClaudeExecutionCwd", "signal"],
    ["src/surface/bridge/subscribe-from-bus.ts", "bridgeBusToAdapter.startRelay", "signal"],
    [
      "src/conversation/thread-summarization-worker.ts",
      "runThreadSummarizationWorkerOperation",
      "signal",
    ],
    ["src/conversation/thread-worker.ts", "rethrowConversationThreadWorkerPanic", "signal"],
    ["src/custom-commands/manager.ts", "importCustomCommandModule", "signal"],
    ["src/custom-commands/manager.ts", "invokeCustomCommand", "signal"],
    ["src/custom-commands/manager.ts", "settleCustomCommand", "signal"],
    ["src/github/github-api.ts", "adaptGithubApiResultToHost.err.<callback>", "signal"],
    ["src/github/github-api.ts", "captureGithubApiExternal", "signal"],
    ["src/github/github-app-token.ts", "captureGithubAppAuth", "signal"],
    ["src/github/github-app.ts", "captureGithubAppFs", "signal"],
    ["src/github/github-app.ts", "readGithubAppPrivateKeyPem.err.<callback>", "signal"],
    ["src/github/github-app.ts", "readGithubAppSecret.err.<callback>", "signal"],
    ["src/github/github-auth.ts", "captureGithubAuthExternal", "signal"],
    ["src/github/github-auth.ts", "getGithubViewerLoginOrThrow.err.<callback>", "signal"],
    ["src/github/github-auth.ts", "getPreferredGithubAuthOrThrow.err.<callback>", "signal"],
    ["src/github/github-auth.ts", "getPreferredGithubAuthOrThrow.ok.<callback>", "signal"],
    ["src/github/github-ids.ts", "parseGithubSessionId", "signal"],
    ["src/github/github-user-token.ts", "captureGithubUserTokenFs", "signal"],
    ["src/github/github-user-token.ts", "readGithubUserTokenSecret.err.<callback>", "signal"],
    ["src/github/github-user-token.ts", "writeGithubUserTokenSecret.err.<callback>", "signal"],
    ["src/github/webhook/github-webhook-server.ts", "captureGithubWebhookOperation", "signal"],
    ["src/plugins/builtin/local-tools.ts", "captureLocalApplyPatchFs", "signal"],
    ["src/tools/fs/remote-media-download.ts", "readRemoteMedia", "signal"],
    ["src/plugins/builtin/local-tools.ts", "signalBuiltinToolHostError", "signal"],
    ["src/plugins/builtin/server-tools.ts", "signalBuiltinPluginSkip", "signal"],
    [
      "src/plugins/manager.ts",
      "createCoreToolPluginManager.adaptPluginResultToHost.err.<callback>",
      "signal",
    ],
    ["src/runtime/core-config-watch.ts", "captureCoreConfigWatchRead", "signal"],
    [
      "src/runtime/create-core-runtime.ts",
      "setupCoreEventBusResources.try.ok.<callback>.err@7.<callback>@1",
      "signal",
    ],
    [
      "src/runtime/create-core-runtime.ts",
      "setupCoreEventBusResources.try.ok.<callback>.err@9.<callback>@2",
      "signal",
    ],
    [
      "src/runtime/create-core-runtime.ts",
      "adaptCoreEventBusCleanupResultToHost.err.<callback>",
      "signal",
    ],
    ["src/runtime/create-core-runtime.ts", "captureCoreEventBusCleanup", "signal"],
    ["src/runtime/create-core-runtime.ts", "captureCoreLilacBusConstruction", "signal"],
    ["src/runtime/create-core-runtime.ts", "captureCoreRawBusConstruction", "signal"],
    ["src/runtime/create-core-runtime.ts", "captureCoreRedisConnection", "signal"],
    ["src/runtime/create-core-runtime.ts", "captureCoreRedisConstruction", "signal"],
    ["src/runtime/create-core-runtime.ts", "captureCoreWorkspacePreparation", "signal"],
    [
      "src/runtime/create-core-runtime.ts",
      "createCoreRuntime.probeRedisHealth.err.<callback>",
      "signal",
    ],
    [
      "src/runtime/create-core-runtime.ts",
      "createCoreRuntime.readCoreConfigParserVersion.err.<callback>",
      "signal",
    ],
    [
      "src/runtime/create-core-runtime.ts",
      "createCoreRuntime.startCoreConfigWatcher.err.<callback>",
      "signal",
    ],
    [
      "src/runtime/create-core-runtime.ts",
      "createCoreRuntime.validateCoreConfigOnChange.err.<callback>",
      "signal",
    ],
    ["src/runtime/create-core-runtime.ts", "createCoreRuntimeCleanupSupervisor.finish", "signal"],
    ["src/shared/event-bus-result.ts", "adaptEventPublishResultToHost", "signal"],
    [
      "src/surface/bridge/subscribe-from-bus.ts",
      "adaptSurfaceOperationToRelay.err.<callback>",
      "signal",
    ],
    ["src/surface/bridge/subscribe-from-bus.ts", "rethrowBusToAdapterPanic", "signal"],
    ["src/surface/discord/discord-adapter.ts", "captureDiscordOperation", "signal"],
    [
      "src/surface/discord/discord-runtime-descriptor.ts",
      "adaptDiscordSkippedOutputCleanupResultToHost.err.<callback>",
      "signal",
    ],
    ["src/surface/github/github-adapter.ts", "parseGithubThreadResult", "signal"],
    ["src/surface/github/github-adapter.ts", "captureGithubOperation", "signal"],
    ["src/tool-server/tools/web-search/shared.ts", "throwIfAborted", "signal"],
    ["src/tool-server/tools/web/page-content.ts", "checkPageSignal", "signal"],
    [
      "src/tool-server/tools/web/browser-page-acquisition.ts",
      "DefaultBrowserPageAcquisition.resolveChromiumLaunchOptions",
      "signal",
    ],
    ["src/tool-server/tools/web/provider-page-extraction.ts", "withAbortSignal", "signal"],
    ["src/tools/tool-result-adapters.ts", "adaptToolResultToHost.err.<callback>", "signal"],
    [
      "src/transcript/transcript-store.ts",
      "SqliteTranscriptStore.migrate.transaction.<callback@1>",
      "signal",
    ],
    [
      "src/conversation/thread-worker.ts",
      "signalConversationThreadWorkerPanicToProcess.queueMicrotask.<callback@1>",
      "signal",
    ],
    [
      "src/github/github-app-token.ts",
      "getGithubInstallationTokenOrThrow.err.<callback>",
      "signal",
    ],
    ["src/github/webhook/github-webhook-server.ts", "superviseGithubWebhookHandler", "signal"],
    ["src/mcp/config-file.ts", "writeMcpConfigFileAtomic.err@5.<callback>@4", "signal"],
    ["src/mcp/config.ts", "serializeMcpConfigYaml.err.<callback>", "signal"],
    ["src/mcp/credential-file.ts", "readMcpOAuthCredentialFile.err.<callback>", "signal"],
    ["src/mcp/credential-file.ts", "readMcpOAuthCredentialFileResult.ok.<callback>", "signal"],
    ["src/mcp/credential-file.ts", "resolveMcpOAuthCredentialPath.err.<callback>", "signal"],
    ["src/mcp/credential-file.ts", "updateMcpOAuthCredentialFile.err.<callback>", "signal"],
    ["src/mcp/credential-file.ts", "writeMcpOAuthCredentialFileAtomic.err.<callback>", "signal"],
    [
      "src/mcp/credential-file.ts",
      "writeMcpOAuthCredentialFileAtomicResult.ok.<callback>.finish",
      "signal",
    ],
    [
      "src/mcp/credential-file.ts",
      "updateMcpOAuthCredentialFileResult.ok.<callback>.then.<callback@1>@1.ok.<callback>",
      "signal",
    ],
    [
      "src/mcp/oauth-provider.ts",
      "McpOAuthProvider.providerForAttempt.attemptProvider.redirectToAuthorization",
      "signal",
    ],
    ["src/mcp/oauth-provider.ts", "McpOAuthProvider.assertActive", "signal"],
    ["src/mcp/oauth-provider.ts", "McpOAuthProvider.clientInformation", "signal"],
    [
      "src/mcp/oauth-provider.ts",
      "McpOAuthProvider.completeAuthorization.err.<callback>",
      "signal",
    ],
    ["src/mcp/oauth-provider.ts", "McpOAuthProvider.rejectImplicitAuthorization", "signal"],
    ["src/mcp/oauth-provider.ts", "McpOAuthProvider.startAuthorization.err.<callback>", "signal"],
    [
      "src/mcp/oauth-provider.ts",
      "McpOAuthProviderService.startAuthorization.err.<callback>",
      "signal",
    ],
    ["src/mcp/registry.ts", "McpRegistry.init.runLifecycle.<callback@1>", "signal"],
    ["src/mcp/registry.ts", "McpRegistry.shutdown.runLifecycle.<callback@1>", "signal"],
    ["src/mcp/registry.ts", "McpRegistry.wrapToolExecution.execute", "signal"],
    ["src/mcp/modern-result-validation.ts", "signalTransportCancellation", "signal"],
    [
      "src/mcp/oauth-provider.ts",
      "McpOAuthProvider.providerForAttempt.attemptProvider.codeVerifier",
      "signal",
    ],
    [
      "src/mcp/oauth-provider.ts",
      "McpOAuthProvider.providerForAttempt.attemptProvider.saveState",
      "signal",
    ],
    [
      "src/runtime/create-core-runtime.ts",
      "createCoreRuntime.probeRedisHealth.try.<callback>.setTimeout.<callback@1>",
      "signal",
    ],
    ["src/surface/bridge/subscribe-from-bus.ts", "superviseBusToAdapterCleanup", "signal"],
    [
      "src/surface/bridge/subscribe-from-bus.ts",
      "adaptBusToAdapterSubscriptionStart.err.<callback>",
      "signal",
    ],
    [
      "src/surface/bridge/subscribe-from-bus.ts",
      "adaptBusToAdapterSubscriptionStop.err.<callback>",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner.ts",
      "adaptModelResolutionToBusRunnerHost.err.<callback>",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/skills-context.ts",
      "maybeBuildSkillsSectionForPrimary",
      "signal",
    ],
    ["src/surface/bridge/bus-agent-runner.ts", "rethrowBusAgentRunnerPanic", "signal"],
    ["src/surface/bridge/bus-agent-runner.ts", "signalBusAgentRunnerHostFailure", "signal"],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "fitImageForAnthropicFallback",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "resolveAnthropicFallbackDownload.promise.<callback>",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/anthropic-fallback-media.ts",
      "resolveAnthropicFallbackDownload",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-named-continuation.ts",
      "adaptContinuationResultToHost.err.<callback>",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-named-continuation.ts",
      "createCoreNamedClaudeRuntime.ok.<callback>.recordSuccessfulModelCall",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
      "adaptContinuationResultToHost.err.<callback>",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
      "createCorePrimaryClaudeRuntime.ok.<callback>.createCandidate",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
      "createCorePrimaryClaudeRuntime.ok.<callback>.materializeAttempt",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/core-primary-continuation.ts",
      "createCorePrimaryClaudeRuntime.ok.<callback>.recordSuccessfulModelCall",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/output-publisher.ts",
      "adaptAgentOutputPublishResultToHost.err.<callback>",
      "signal",
    ],
    [
      "src/surface/bridge/bus-agent-runner/prompt-overlays.ts",
      "resolveSessionAdditionalPrompts",
      "signal",
    ],
    [
      "src/surface/discord/discord-request-router.ts",
      "adaptDiscordRequestRouterStartOutcomeToHost",
      "signal",
    ],
    [
      "src/surface/discord/discord-request-router.ts",
      "adaptDiscordRequestRouterStartOutcomeToHost.err.<callback>",
      "signal",
    ],
    [
      "src/surface/discord/discord-request-router.ts",
      "adaptRouterSubscriptionsStop.err.<callback>",
      "signal",
    ],
    ["src/surface/discord/discord-request-router.ts", "captureRouterActiveBatchGate", "signal"],
    ["src/surface/discord/discord-request-router.ts", "captureRouterRouting", "signal"],
    [
      "src/surface/discord/discord-request-router.ts",
      "signalDiscordRequestRouterPlatformMismatch",
      "signal",
    ],
    [
      "src/surface/discord/discord-request-router.ts",
      "startDiscordRequestRouter.evaluateAdapterSuppression",
      "signal",
    ],
    [
      "src/surface/discord/discord-request-router.ts",
      "startDiscordRequestRouter.evaluateDirectReplyRouterGate",
      "signal",
    ],
    [
      "src/surface/discord/discord-request-router.ts",
      "startDiscordRequestRouter.reloadCoreConfigIfNeeded",
      "signal",
    ],
    ["src/surface/discord/discord-request-router/common.ts", "getDiscordFlags", "signal"],
    ["src/ssh/ssh-exec.ts", "sshExecScriptJson.err@4.<callback>", "signal"],
    [
      "src/surface/bridge/request-composition/attachments.ts",
      "appendDiscordAttachmentsToUserContent",
      "signal",
    ],
    [
      "src/surface/bridge/request-composition/attachments.ts",
      "downloadDiscordAttachment",
      "signal",
    ],
    ["src/surface/bridge/request-composition/attachments.ts", "resolveOwnedFileData", "signal"],
    ["src/surface/bridge/publish-to-bus.ts", "bridgeAdapterToBus.subscribe.<callback@1>", "signal"],
    [
      "src/surface/discord/discord-adapter.ts",
      "DiscordAdapter.connect.err@1.<callback>@1",
      "signal",
    ],
    [
      "src/surface/discord/discord-adapter.ts",
      "DiscordAdapter.connect.err@2.<callback>@2",
      "signal",
    ],
    ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.disconnect", "signal"],
    ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.getSelf", "signal"],
    ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.fetchGuildIdForChannel", "signal"],
    ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.fetchDiscordMessage", "signal"],
    ["src/surface/discord/discord-adapter.ts", "DiscordAdapter.fetchDiscordMessages", "signal"],
    [
      "src/surface/discord/output/discord-output-stream.ts",
      "DiscordOutputStream.ensureStarted",
      "signal",
    ],
    [
      "src/surface/discord/output/discord-output-stream.ts",
      "adaptDiscordOutputResultToHost.err.<callback>",
      "signal",
    ],
    [
      "src/surface/discord/output/discord-output-stream.ts",
      "DiscordOutputStream.finishOutput",
      "signal",
    ],
    [
      "src/tool-server/create-tool-server.ts",
      "signalFatalToolCallDefectToProcess.queueMicrotask.<callback@1>",
      "signal",
    ],
    ["src/tool-server/create-tool-server.ts", "adaptPanicToToolServerHost", "signal"],
    ["src/tool-server/create-tool-server.ts", "adaptResultToHost.err.<callback>", "signal"],
    [
      "src/runtime/create-core-runtime.ts",
      "createCoreRuntime.start.try.<callback>.runSummarization.err.<callback>",
      "signal",
    ],
    [
      "src/tool-server/health-state.ts",
      "createToolServerHealthState.captureActiveLevel1Work",
      "signal",
    ],
    [
      "src/tool-server/health-state.ts",
      "createToolServerHealthState.captureRuntimeDiagnostics",
      "signal",
    ],
    ["src/tool-server/health-state.ts", "createToolServerHealthState.getSnapshot", "signal"],
    [
      "src/tool-server/tools/web/direct-http-page-acquisition.ts",
      "adaptDirectHttpPageResultToHost.err.<callback>",
      "signal",
    ],
    [
      "src/tool-server/tools/web-search/exa-web-search-provider.ts",
      "adaptExaProviderResultToHost.err.<callback>",
      "signal",
    ],
    [
      "src/tool-server/tools/web-search/firecrawl-web-search-provider.ts",
      "adaptFirecrawlSearchResultToProviderHost.err.<callback>",
      "signal",
    ],
    [
      "src/tool-server/tools/web-search/tavily-web-search-provider.ts",
      "adaptTavilyProviderResultToHost.err.<callback>",
      "signal",
    ],
    [
      "src/tool-server/health-state.ts",
      "createToolServerHealthState.signalWatchdogDefect.queueMicrotask.<callback@1>",
      "signal",
    ],
    ["src/tool-server/tools/web-search/shared.ts", "withAbortSignal.<callback>.onAbort", "signal"],
    [
      "src/tool-server/tools/web/provider-page-extraction.ts",
      "withAbortSignal.<callback>.onAbort",
      "signal",
    ],
    [
      "src/workflow/workflow-engine.ts",
      "WorkflowEngine.claimAndLaunch.catch.<callback@1>",
      "signal",
    ],
    ["src/workflow/workflow-engine.ts", "WorkflowEngine.waitForAgentRequest", "signal"],
    [
      "src/workflow/workflow-live-parent-bridge.ts",
      "WorkflowLiveParentBridge.registerParent.listPending.map.<callback@1>",
      "signal",
    ],
    ["src/workflow/workflow-sandbox-child.js", "send", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "jsonClone", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "parseCallSiteManifest", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "decodeInputMessage", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "hostCall", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "lockDownPrimordials.value", "signal"],
    ["src/workflow/workflow-sandbox-child.js", "start", "signal"],
    ["src/workflow/workflow-trigger-scheduler.ts", "WorkflowTriggerScheduler.tick", "signal"],
  ],
  "apps/mini-lilac": [
    ["build.ts", "captureBuildOperation", "signal"],
    ["build.ts", "signalBuildFailure", "signal"],
    ["install-local.ts", "captureInstallOperation", "signal"],
    ["install-local.ts", "signalLocalInstallFailure", "signal"],
    ["src/main.ts", "captureCommand", "signal"],
  ],
  "apps/mini-lilac-server": [
    ["src/main.ts", "acquireDatabaseLock", "signal"],
    ["src/main.ts", "adaptLifecycleResultToHost", "signal"],
    ["src/main.ts", "captureNodeCliParsing", "signal"],
    ["src/main.ts", "captureServerCleanup", "signal"],
    ["src/main.ts", "captureServerOperation", "signal"],
    ["src/main.ts", "rethrowPanic", "signal"],
    ["src/main.ts", "shutdownMiniLilacServer", "signal"],
    ["src/server.ts", "adaptMiniLilacPersistenceResultToHost", "signal"],
    ["src/server.ts", "canonicalDirectory", "signal"],
    ["src/server.ts", "classifyHttpOperationFailure", "signal"],
    ["src/server.ts", "enqueueSseKeepAlive", "signal"],
    ["src/server.ts", "signalMiniLilacServerConfigurationFailure", "signal"],
    ["src/server.ts", "signalMiniLilacServerPanicToProcess.queueMicrotask.<callback@1>", "signal"],
    ["src/main.ts", "shutdownMiniLilacServerResult.settleLifecycleResult.<callback@2>", "signal"],
    ["src/server.ts", "pumpSseBody.<callback>", "signal"],
  ],
  "apps/mini-lilac-tui": [["src/failure-adapter.ts", "signalTuiDefect", "signal"]],
  "apps/tool-bridge": [["client.ts", "signalBridgeDefect", "signal"]],
  "packages/agent": [
    ["adapters/openai-responses/socket.ts", "signalSocketCloseFailure", "signal"],
    ["agent-tool-host.ts", "signalExternalToolCallHost", "signal"],
    ["agent-tool-host.ts", "AgentToolHost.executeExternalToolCall.map.<callback@1>", "signal"],
    ["message-clone.ts", "snapshotAgentMessage", "signal"],
    ["agent-executor.ts", "AgentExecutor.finishIdleRecovery", "signal"],
    ["agent-executor.ts", "AgentExecutor.runLoop.<callback>", "signal"],
    ["agent-runtime-support.ts", "signalAgentStateHost", "signal"],
    ["agent-runtime-support.ts", "signalExternalToolCallHost", "signal"],
    ["atomic-tool-execution.ts", "signalAtomicToolExecutionHost", "signal"],
    ["auto-compaction.ts", "attachAutoCompaction.canonicalModelCallPreflight", "signal"],
    ["auto-compaction.ts", "signalAutoCompactionHost", "signal"],
    ["failure-adapters.ts", "rethrowAgentPanic", "signal"],
    ["openai-server-compaction.ts", "compactWithOpenAIResponses", "signal"],
    ["session-continuation.ts", "signalCanonicalJsonInvalid", "signal"],
    ["transient-model-retry.ts", "createTransientModelRetryController.handler", "signal"],
  ],
  "packages/bash-safety": [
    ["src/analyze/analyze-command.ts", "parseBashCommand", "signal"],
    ["src/rules-filesystem.ts", "readGitMetadataFile", "signal"],
    ["src/rules-rm.ts", "resolveRmPaths", "signal"],
  ],
  "packages/blob-storage": [],
  "packages/claude-code-bridge": [
    ["claude-code-agent-adapter.ts", "signalClaudeAdapterHost", "signal"],
    ["claude-attempt-runtime-owner.ts", "ClaudeAttemptRuntimeOwner.prepare", "signal"],
    [
      "claude-attempt-runtime-owner.ts",
      "ClaudeAttemptRuntimeOwner.adaptRunEndRetirementToHost",
      "signal",
    ],
    [
      "claude-attempt-runtime-owner.ts",
      "ClaudeAttemptRuntimeOwner.getNativeInputEstimateFloor",
      "signal",
    ],
    [
      "claude-attempt-runtime-owner.ts",
      "ClaudeAttemptRuntimeOwner.recordSuccessfulModelCall",
      "signal",
    ],
    [
      "claude-attempt-runtime-owner.ts",
      "ClaudeAttemptRuntimeOwner.retireForCanonicalReplacement",
      "signal",
    ],
    ["claude-attempt-runtime-owner.ts", "ClaudeAttemptRuntimeOwner.retireForRetry", "signal"],
    ["claude-attempt-runtime-owner.ts", "captureCandidateFactory", "signal"],
    ["claude-code-run.ts", "captureClaudeContextUsage", "signal"],
    ["claude-code-run.ts", "captureCleanupOperationSync", "signal"],
    ["claude-code-run.ts", "captureExternalOperation", "signal"],
    ["claude-code-run.ts", "captureExternalOperationSync", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRun", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.clear", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.clearResult", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.drainQueryControllers", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.settleExecutionResult", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.finalizeToHost", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.spawnTrackedProcess", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.waitForObservability", "signal"],
    ["claude-code-run.ts", "settleQueryAndProcess", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.disposeResult.<callback>", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.dispose.<callback>", "signal"],
    ["claude-code-run.ts", "materializeClaudeCodeRunResult.finalizeResult.<callback>", "signal"],
    [
      "claude-code-tools.ts",
      "createClaudeCodeToolBridgeResult.setRequestHandler.<callback@2>@2",
      "signal",
    ],
    ["claude-code-tools.ts", "createClaudeCodeToolBridge", "signal"],
    ["claude-code-tools.ts", "createClaudeCodeToolBridgeResult", "signal"],
    ["claude-code-tools.ts", "createClaudeCodeToolBridgeResult.close", "signal"],
    ["claude-code-tools.ts", "createClaudeCodeToolBridgeResult.closeResult", "signal"],
    ["claude-code-tools.ts", "mapToolResultOutputToMcp", "signal"],
    ["claude-code-tools.ts", "stringifyJson", "signal"],
    ["claude-code-tools.ts", "validateClaudeCodeBuiltInTools", "signal"],
  ],
  "packages/coding-tools": [
    ["src/bash.ts", "createBashSpool.close", "signal"],
    ["src/batch.ts", "resolveBatchEditTargets", "signal"],
    ["src/batch.ts", "validateInput", "signal"],
    ["src/buffered-file-sink.ts", "BufferedFileSink.open", "signal"],
    ["src/buffered-file-sink.ts", "continueBufferedSinkQueue", "signal"],
    ["src/host-compatibility.ts", "adaptCodingToolResultToHost", "signal"],
  ],
  "packages/event-bus": [
    ["event-dead-letter.ts", "checkedDeadLetterAcceptance", "signal"],
    ["lilac-bus.ts", "checkedDisposition", "signal"],
    ["lilac-bus.ts", "createLilacBus.bus.subscribeTopic.subscribe.<callback@3>", "signal"],
    ["lilac-bus.ts", "createLilacBus.bus.close", "signal"],
    ["lilac-bus.ts", "createLilacBus.bus.getTopicWatermark", "signal"],
    ["lilac-bus.ts", "createLilacBus.bus.publish", "signal"],
    ["lilac-bus.ts", "createLilacBus.bus.retireTopicConsumerGroup", "signal"],
    ["lilac-bus.ts", "createLilacBus.bus.trimTopicBeforeCheckpoint", "signal"],
    ["redis-connection-pool.ts", "RedisConnectionPool.createConnection", "signal"],
    ["redis-event-dead-letter.ts", "RedisEventDeadLetter.prepare", "signal"],
    ["redis-event-dead-letter.ts", "RedisEventDeadLetter.serverTimeMs", "signal"],
    ["redis-managed-delivery.ts", "managedRedisPhysicalGroup", "signal"],
    ["redis-managed-delivery.ts", "managedRedisRetryDelayMs", "signal"],
    ["redis-managed-delivery.ts", "panic", "signal"],
    ["redis-managed-delivery.ts", "assertId", "signal"],
    ["redis-managed-delivery.ts", "assertLeaseForId", "signal"],
    ["redis-managed-delivery.ts", "assertTerminalMaterial", "signal"],
    ["redis-managed-delivery.ts", "RedisManagedDelivery.constructor", "signal"],
    ["redis-managed-delivery.ts", "RedisManagedDelivery.scheduleRetry", "signal"],
    ["redis-streams-bus.ts", "deliveryAction", "signal"],
    ["redis-streams-bus.ts", "ensureGroup", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.close", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.fetch", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.flushPendingTrims", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.publish", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.retireConsumerGroup", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.subscribe.handleTailEntry", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.subscribe.runTailLoop", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.subscribe.runDurableLoop", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.subscribe.runDurableLoop.captureTransport", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.subscribe.runDurableLoop.handleLeaseLoss", "signal"],
    [
      "redis-streams-bus.ts",
      "RedisStreamsBus.subscribe.runDurableLoop.loadRecoveryEntry.captureTransport.<callback@1>",
      "signal",
    ],
    [
      "redis-streams-bus.ts",
      "RedisStreamsBus.subscribe.runDurableLoop.deadLetterManaged",
      "signal",
    ],
    [
      "redis-streams-bus.ts",
      "RedisStreamsBus.subscribe.runDurableLoop.handleManagedEntry",
      "signal",
    ],
    [
      "redis-streams-bus.ts",
      "RedisStreamsBus.subscribe.runDurableLoop.invokeManagedEntry",
      "signal",
    ],
    ["redis-streams-bus.ts", "RedisStreamsBus.trimAcknowledgedPrefix", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.trimBeforeCheckpoint", "signal"],
    ["redis-streams-bus.ts", "RedisStreamsBus.watermark", "signal"],
    [
      "redis-event-dead-letter.ts",
      "RedisEventDeadLetter.accept.captureDeadLetterAcceptance.<callback@1>",
      "signal",
    ],
  ],
  "packages/fs": [
    ["src/filesystem-operation.ts", "captureFilesystemOperation", "signal"],
    ["src/filesystem-operation.ts", "captureFilesystemOperationSync", "signal"],
    ["src/fs-impl.ts", "compileEditRegex", "signal"],
    ["src/remote-runner-protocol.ts", "decodeJson", "signal"],
    ["src/ripgrep.ts", "decodeRipgrepMatchLine", "signal"],
    ["src/ripgrep.ts", "ripgrep", "signal"],
    ["src/search-backend.ts", "captureFffOperation", "signal"],
    ["src/search-backend.ts", "captureFffSyncOperation", "signal"],
  ],
  "packages/mini-lilac-client": [
    ["mini-lilac-transport.ts", "parseMiniLilacStream.pull", "signal"],
    ["mini-lilac-transport.ts", "parseMiniLilacStream.transform", "signal"],
    ["mini-lilac-transport.ts", "resultToMiniLilacCompatibilityFailure", "signal"],
    ["mini-lilac-transport.ts", "throwMiniLilacPanic", "signal"],
  ],
  "packages/mini-lilac-runtime": [
    [
      "src/session-service.ts",
      "signalMiniLilacRuntimePanicToProcess.queueMicrotask.<callback@1>",
      "signal",
    ],
    ["src/workspace-history-store.ts", "superviseOutcome.rejection.reject", "signal"],
    ["src/workspace-history-store.ts", "throwFailure", "signal"],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.constructor", "signal"],
    [
      "src/workspace-history-store.ts",
      "WorkspaceHistoryStore.withWorkspaceLockOutcome.withStoreLock.<callback@2>.captureResult",
      "signal",
    ],
    [
      "src/workspace-history-store.ts",
      "WorkspaceHistoryStore.withWorkspaceLockOutcome.withStoreLock.<callback@2>.lockedStore.invalidateCaptureCacheResult",
      "signal",
    ],
    [
      "src/workspace-history-store.ts",
      "WorkspaceHistoryStore.withWorkspaceLockOutcome.withStoreLock.<callback@2>.lockedStore.prepareRestore",
      "signal",
    ],
    [
      "src/workspace-history-store.ts",
      "WorkspaceHistoryStore.withWorkspaceLockOutcome.withStoreLock.<callback@2>.lockedStore.resumePreparedRestore",
      "signal",
    ],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.withWorkspaceLockResult", "signal"],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.resumeLocked", "signal"],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.publicResult", "signal"],
    [
      "src/workspace-history-store.ts",
      "WorkspaceHistoryStore.validateSourceGitDirectory",
      "signal",
    ],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.runGit", "signal"],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.runPrivateGitToHandle", "signal"],
    ["src/workspace-history-store.ts", "WorkspaceHistoryStore.withWorkspaceLock", "signal"],
    [
      "src/workspace-history-store.ts",
      "WorkspaceHistoryStore.withWorkspaceLockOutcome.withStoreLock.<callback@2>.lockedStore.capture",
      "signal",
    ],
    ["src/config.ts", "loadRuntimeConfig", "signal"],
    ["src/config.ts", "throwRuntimeConfigPanic", "signal"],
    ["src/model-catalog.ts", "ModelCatalog.constructor", "signal"],
    ["src/model-catalog.ts", "ModelCatalog.get", "signal"],
    ["src/model-catalog.ts", "parseModelRef", "signal"],
    ["src/model-catalog.ts", "resolveLanguageModel", "signal"],
    ["src/model-catalog.ts", "throwModelCatalogPanic", "signal"],
    ["src/providers.ts", "createAiProviderRegistry", "signal"],
    ["src/providers.ts", "loadProviderAuth", "signal"],
    ["src/providers.ts", "loadProviderConfig", "signal"],
    ["src/providers.ts", "loadProviderRegistry", "signal"],
    ["src/providers.ts", "throwProviderPanic", "signal"],
    ["src/providers.ts", "writeProviderAuth", "signal"],
    ["src/session-service.ts", "rethrowSessionPanic", "signal"],
    ["src/session-service.ts", "SessionActor.commitSteeringBoundary", "signal"],
    [
      "src/session-service.ts",
      "SessionActor.commitSteeringBoundary.withWorkspaceLock.<callback@1>.map.<callback@1>@1",
      "signal",
    ],
    ["src/session-service.ts", "SessionActor.createAgent", "signal"],
    ["src/session-service.ts", "SessionActor.createAgent.createCandidate", "signal"],
    ["src/session-service.ts", "SessionActor.createAgent.execute", "signal"],
    ["src/session-service.ts", "SessionActor.createAgent.materializeAttempt", "signal"],
    ["src/session-service.ts", "SessionActor.delegate", "signal"],
    ["src/session-service.ts", "SessionActor.executeTopLevelRun", "signal"],
    ["src/session-service.ts", "SessionActor.generateSessionTitle", "signal"],
    ["src/session-service.ts", "SessionActor.replaceTodos.withLock.<callback@1>", "signal"],
    [
      "src/session-service.ts",
      "SessionActor.replaceTodos.withLock.<callback@1>.then.<callback@1>@1",
      "signal",
    ],
    ["src/session-service.ts", "sessionResultToCompatibility", "signal"],
    ["src/session-service.ts", "SessionService.constructor", "signal"],
    ["src/session-service.ts", "SessionService.constructor.<callback>@2", "signal"],
    ["src/skills.ts", "MiniLilacSkillCatalogSnapshot.load", "signal"],
    ["src/skills.ts", "throwSkillPanic", "signal"],
    ["src/sqlite-persistence-codec.ts", "decodePlainJson", "signal"],
    ["src/sqlite-persistence-codec.ts", "decodeSuperJson", "signal"],
    ["src/sqlite-store.ts", "canonicalCommandPayloadResult", "signal"],
    ["src/sqlite-store.ts", "captureMiniLilacCleanup.rethrow", "signal"],
    ["src/sqlite-store.ts", "closeMiniLilacHistoryRecoveryDatabase", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.acquireCloseBlocker", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.admitRootPromptHistory", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.assertConservativeProviderTransition", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.assertHeadsEqualState", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.assertStateConnectedToRoot", "signal"],
    [
      "src/sqlite-store.ts",
      "MiniLilacSqliteStore.assertWorkspaceHistoryAvailableForOwner",
      "signal",
    ],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.close", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.closeAfterInitializationFailure", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.commitEmptyHistoryNavigation", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.commitHistoryCompaction", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.commitSteeringHistoryBoundary", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.constructor", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.decodeTranscriptNodeValue", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.deleteHistoryOperationRow", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.deletePendingRunFinalizationRow", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.getIncomingHistoryTransition", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.initializeSchemaResult", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.insertHistoryTransitionRow", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.internSerializedChain", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.moveHistoryCursor", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.parseHistoryNavigationResult", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.requireQuiescentHistorySession", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.reserveHistoryOperation", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.reservePendingRunFinalization", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.restoreSchemaMigrationPragmas", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.runHistoryReadResult", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.saveHistoryCommandResult", "signal"],
    ["src/sqlite-store.ts", "MiniLilacSqliteStore.validateHistoryTransitionDestination", "signal"],
    ["src/sqlite-store.ts", "readMiniLilacHistoryRecoveryStatusResult", "signal"],
    ["src/sqlite-store.ts", "serializeStoreValueResult", "signal"],
    ["src/sqlite-store.ts", "storeResultToLegacy", "signal"],
    ["src/sqlite-store.ts", "throwPrimaryAfterCleanup", "signal"],
    ["src/sqlite-todo-persistence-codec.ts", "decodeMiniLilacTodos", "signal"],
    ["src/sqlite-todo-persistence-codec.ts", "readMiniLilacTodos", "signal"],
    ["src/webfetch.ts", "throwWebfetchPanic", "signal"],
    ["src/webfetch.ts", "webfetchResultToLegacyOutput", "signal"],
    ["src/session-service.ts", "SessionActor.startPrompt.withLock.<callback@1>", "signal"],
    [
      "src/session-service.ts",
      "SessionActor.commitSteeringBoundary.withWorkspaceLock.<callback@1>",
      "signal",
    ],
    [
      "src/session-service.ts",
      "SessionActor.commitRunFinalization.withWorkspaceLock.<callback@1>",
      "signal",
    ],
    ["src/session-service.ts", "SessionActor.steer.withLock.<callback@1>", "signal"],
    ["src/session-service.ts", "SessionActor.cancel.withLock.<callback@1>", "signal"],
    ["src/session-service.ts", "SessionActor.compact.withLock.<callback@1>", "signal"],
    ["src/session-service.ts", "SessionActor.updateBindings.withLock.<callback@1>", "signal"],
    [
      "src/session-service.ts",
      "SessionService.promptDelegatedSession.withDelegatedSessionLock.<callback@2>",
      "signal",
    ],
    ["src/webfetch.ts", "inspectHtml.captureWebfetchSync.<callback@1>.onopentag", "signal"],
  ],
  "packages/remote-fs-runner": [
    ["src/cli.ts", "preservePanic", "signal"],
    ["src/cli.ts", "runWithStartupLockCleanup", "signal"],
  ],
  "packages/plugin-runtime": [
    ["capabilities.ts", "capturePluginInspection", "signal"],
    ["discovery.ts", "captureFileOperation", "signal"],
    ["discovery.ts", "decodePluginPackageJsonText", "signal"],
    ["hooks.ts", "captureAsyncHook", "signal"],
    ["hooks.ts", "captureSyncHook", "signal"],
    ["loader.ts", "loadToolPluginModuleCapability", "signal"],
    ["manager.ts", "ToolPluginManager.finishCleanup", "signal"],
    ["manager.ts", "ToolPluginManager.registerPluginPreservingPanic", "signal"],
    ["manager.ts", "captureManagerHook", "signal"],
  ],
  "packages/tool-results": [
    ["src/tool-result-artifact-store.ts", "adaptToolResultArtifactReadToAvailability", "signal"],
    [
      "src/tool-result-artifact-store.ts",
      "adaptToolResultArtifactReadToUnavailablePolicy",
      "signal",
    ],
    [
      "src/tool-result-artifact-store.ts",
      "createToolResultArtifactStore.readEncryptedWindow.<callback>",
      "signal",
    ],
    ["src/tool-result-artifact-store.ts", "adaptToolResultArtifactStoreInitToHost", "signal"],
    [
      "src/tool-result-artifact-store.ts",
      "createToolResultArtifactStore.captureOperation",
      "signal",
    ],
    ["src/tool-result-artifact-store.ts", "createToolResultArtifactStore.decrypt", "signal"],
    ["src/tool-result-artifact-store.ts", "createToolResultArtifactStore.encrypt", "signal"],
    [
      "src/tool-result-artifact-store.ts",
      "createToolResultArtifactStore.readEncryptedWindow",
      "signal",
    ],
    ["src/tool-result-artifact-store.ts", "createToolResultArtifactStore.readMetadata", "signal"],
    [
      "src/tool-result-artifact-store.ts",
      "createToolResultArtifactStore.writeEncryptedStreamAtomic",
      "signal",
    ],
    ["src/tool-result-output-normalizer.ts", "serializeOutput", "signal"],
  ],
  "packages/utils": [
    ["agent-prompts.ts", "exists", "signal"],
    ["agent-prompts.ts", "loadPromptTemplateState", "signal"],
    ["agent-prompts.ts", "parsePromptTemplateState", "signal"],
    ["agent-prompts.ts", "promptWorkspaceSignature", "signal"],
    ["agent-prompts.ts", "readTextIfExists", "signal"],
    ["build-info.ts", "getBuildInfoFileCacheKey", "signal"],
    ["build-info.ts", "readBuildInfoFile", "signal"],
    ["build-info.ts", "readGitBuildInfo", "signal"],
    ["codex-oauth.ts", "readCodexTokens", "signal"],
    ["codex-oauth.ts", "clearCodexTokens", "signal"],
    ["codex-oauth.ts", "clearCodexTokensResult", "signal"],
    ["codex-oauth.ts", "decodeCodexTokens", "signal"],
    ["codex-oauth.ts", "exchangeCodeForTokens", "signal"],
    ["codex-oauth.ts", "exchangeCodeForTokensResult", "signal"],
    ["codex-oauth.ts", "parseCodexOAuthCallback", "signal"],
    ["codex-oauth.ts", "parseJwtClaims", "signal"],
    ["codex-oauth.ts", "readCodexTokensResult", "signal"],
    ["codex-oauth.ts", "refreshAccessToken", "signal"],
    ["codex-oauth.ts", "refreshAccessTokenResult", "signal"],
    ["codex-oauth.ts", "startCodexOAuthLogin.exchange", "signal"],
    ["codex-oauth.ts", "startCodexOAuthLogin.runExchangeResult", "signal"],
    ["codex-oauth.ts", "startCodexOAuthLogin", "signal"],
    ["codex-oauth.ts", "writeCodexTokens", "signal"],
    ["codex-oauth.ts", "writeSecretFileResult", "signal"],
    ["core-config.ts", "decodeCoreConfigYaml", "signal"],
    ["core-config.ts", "getCoreConfig", "signal"],
    ["core-config.ts", "parseCoreConfig", "signal"],
    ["core-config.ts", "readCoreConfigVersion", "signal"],
    ["core-config.ts", "resolveDiscordToken", "signal"],
    ["core-config/v1.ts", "parseCoreConfigV1ToUniversal", "signal"],
    ["core-config/v2.ts", "parseCoreConfigV2ToUniversal", "signal"],
    ["custom-commands.ts", "decodeCustomCommandResult", "signal"],
    ["custom-commands.ts", "discoverCustomCommands", "signal"],
    ["custom-commands.ts", "pathExists", "signal"],
    ["custom-commands.ts", "readCustomCommandDefinition", "signal"],
    ["find-root.ts", "findWorkspaceRoot", "signal"],
    ["find-root.ts", "hasWorkspacesFieldResult", "signal"],
    ["friendly-units.ts", "parseFriendlyByteSize", "signal"],
    ["friendly-units.ts", "parseFriendlyDurationMs", "signal"],
    ["llm-wire-debug.ts", "JsonlWriter.append", "signal"],
    ["llm-wire-debug.ts", "captureNonStreamingResponse", "signal"],
    ["llm-wire-debug.ts", "consumeSseDebugStream", "signal"],
    ["llm-wire-debug.ts", "createWriter", "signal"],
    ["llm-wire-debug.ts", "decodeRequestBody", "signal"],
    ["llm-wire-debug.ts", "safeParseJson", "signal"],
    ["llm-wire-debug.ts", "withLlmWireDebugFetch.<callback>", "signal"],
    ["logging.ts", "OpenObserveJsonlStream.write", "signal"],
    ["logging.ts", "reportOpenObserveDiagnostics", "signal"],
    ["logging.ts", "safeJsonStringify", "signal"],
    ["logging.ts", "signalOpenObservePanic.queueMicrotask.<callback@1>", "signal"],
    ["model-capability.ts", "ModelCapability.loadRegistryResult.<callback>", "signal"],
    ["model-capability.ts", "ModelCapability.resolve", "signal"],
    ["model-capability.ts", "parseModelSpecifier", "signal"],
    ["model-provider.ts", "createCodexOAuthProvider.<callback>", "signal"],
    ["model-provider.ts", "createCodexOAuthProvider.<callback>.refreshIfNeeded", "signal"],
    [
      "model-provider.ts",
      "createCodexOAuthProvider.<callback>.refreshIfNeeded.<callback>",
      "signal",
    ],
    ["model-provider.ts", "decodeCodexResponsesRequestBody", "signal"],
    ["model-provider.ts", "normalizeCodexResponsesRequestRecord", "signal"],
    ["model-slot.ts", "fromDurableResolvedModelPlan", "signal"],
    ["model-slot.ts", "fromDurableResolvedModelRequest", "signal"],
    ["model-slot.ts", "resolveModelChain", "signal"],
    ["model-slot.ts", "resolveModelPlan", "signal"],
    ["model-slot.ts", "resolveModelRef", "signal"],
    ["model-slot.ts", "resolveModelSlot", "signal"],
    ["openai-responses-connection.ts", "resolveOpenAIResponsesConnectionOptions", "signal"],
    ["openai-responses-connection.ts", "connectOpenAIResponsesWebSocket.<callback>.fail", "signal"],
    ["openai-responses-connection.ts", "connectOpenAIResponsesWebSocket.<callback>", "signal"],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.websocketFetch.start.onMessage.<callback>",
      "signal",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.closeSocket",
      "signal",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.websocketFetch.start.onAbort",
      "signal",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.websocketFetch.start.onClose",
      "signal",
    ],
    [
      "openai-responses-websocket-fetch.ts",
      "createOpenAIResponsesWebSocketFetch.websocketFetch",
      "signal",
    ],
    ["openai-responses-websocket-fetch.ts", "decodeResponsesRequestBody", "signal"],
    ["openai-responses-websocket-fetch.ts", "signalResponsesStreamError", "signal"],
    ["server-compaction-request.ts", "prepareServerCompactionRequestResult", "signal"],
    ["server-compaction-request.ts", "withServerCompactionRequestFetch.wrappedFetch", "signal"],
    ["skills.ts", "parseSkillMarkdown", "signal"],
    ["skills.ts", "parseSkillMarkdownResult", "signal"],
    ["skills.ts", "pathExists", "signal"],
    ["skills.ts", "readTextPrefixResult", "signal"],
    ["skills.ts", "scanSkillPathsBounded", "signal"],
  ],
} as const satisfies Readonly<Record<string, readonly PreciseExceptionIdentity[]>>;
