export const DEFAULT_DISCORD_WORKING_INDICATORS = [
  "Alchemizing",
  "Aromatizing",
  "Assembling",
  "Beboppin'",
  "Bleeping",
  "Blooming",
  "Blooping",
  "Blossoming",
  "Blue Bossa-ing",
  "Bouqueting",
  "Brainstorming",
  "Bubbling",
  "Calibrating",
  "Carbonating",
  "Cascading",
  "Catalyzing",
  "Catching the groove",
  "Compiling",
  "Comping",
  "Composing",
  "Crystallizing",
  "Daydreaming",
  "Dazzling",
  "Decanting",
  "Deducing",
  "Defragmenting",
  "Distilling",
  "Dolphin Dancing",
  "Doodling",
  "Effervescing",
  "Embroidering",
  "Entering Monk's Dream",
  "Extrapolating",
  "Fascinating",
  "Fathoming",
  "Fermenting",
  "Fiddling",
  "Finding the pocket",
  "Finessing",
  "Fizzing",
  "Flatting the Fifth",
  "Flourishing",
  "Footprinting",
  "Formulating",
  "Freeloading",
  "Fully Altering the Dominant",
  "Gallivanting",
  "Gesticulating",
  "Getting Misty",
  "Glimmering",
  "Grooving",
  "Harmonizing",
  "Hitting the changes",
  "Humming",
  "Illuminating",
  "Improvising",
  "Infusing",
  "Investigating",
  "Jamming",
  "Juggling",
  "Lavenderizing",
  "Laying down tracks",
  "Materializing",
  "Meandering",
  "Nebulizing",
  "Noodling",
  "Oleo-ing",
  "Orchestrating",
  "Origami-ing",
  "Parsing",
  "Perambulating",
  "Perfuming",
  "Permutating",
  "Petalling",
  "Philosophizing",
  "Photosynthesizing",
  "Phytomerizing",
  "Ping-ponging",
  "Pinging",
  "Pirouetting",
  "Playing it cool like Miles",
  "Playing the head",
  "Plucking",
  "Polishing",
  "Pollinating",
  "Pruning",
  "Radiating",
  "Recalibrating",
  "Resonating",
  "Reverberating",
  "Riffing",
  "Rummaging",
  "Sashaying",
  "Scatting",
  "Scenting",
  "Scrutinizing",
  "Sequestering Days",
  "Sharping the Ninth",
  "Shedding Peggy's Blue Skylight",
  "Shedding Rhythm Changes",
  "Shimmering",
  "Sifting",
  "Soloing",
  "Sparkling",
  "Spiraling",
  "Sprinkling",
  "Sprouting",
  "Steeping",
  "Sublimating",
  "Substituting the Tritone",
  "Summertiming",
  "Swinging",
  "Synchronizing",
  "Syncopating",
  "Taking Giant Steps",
  "Taking it to the bridge",
  "Taking the A Train",
  "Tessellating",
  "Tiptoeing",
  "Trading fours",
  "Tuning",
  "Twiddling",
  "Twinkling",
  "Unscrambling",
  "Vamping",
  "Waltzing",
  "Weaving",
  "Whispering",
  "Whittling",
  "Whizzing",
  "Working the turnaround",
  "Zesting",
] as const;

export const ENGINEERING_DISCORD_WORKING_INDICATORS_EN = [
  "Appeasing the Linter",
  "Caching the Cosmos",
  "Chasing a Heisenbug",
  "Convincing DNS",
  "Deploying Hope",
  "Feeding the Garbage Collector",
  "Hydrating the Frontend",
  "Rebasing Reality",
  "Taming the Merge Dragon",
  "YAML Whispering",
] as const;

export const ENGINEERING_DISCORD_WORKING_INDICATORS_ZH = [
  "安撫 Linter 到點頭",
  "把 Deploy 當放天燈",
  "把 Log 當籤詩解",
  "把 Merge 衝突哄睡",
  "跟 DNS 講道理",
  "跟 TypeScript 喬條件",
  "在 Kubernetes 裡找出口",
  "對著 YAML 念咒",
  "替 Cache 點香拜拜",
  "追捕海森堡蟲",
] as const;

export const CHUUNI_DISCORD_WORKING_INDICATORS_EN = [
  "Binding Bugs into Sigils",
  "Consulting the Prophecy Logs",
  "Carving Types into Stone",
  "Negotiating with the Void Pointer",
  "Sealing the Release Scroll",
  "Signing the Commit in Moonlight",
  "Summoning the Build Spirits",
  "Walking the Stack Trace Labyrinth",
  "Whispering to the Compiler",
  "Stitching Time in the Event Loop",
] as const;

export const CHUUNI_DISCORD_WORKING_INDICATORS_ZH = [
  "把 Bug 鎖進符印",
  "翻閱預言般的 Logs",
  "以型別刻下誓約",
  "與虛無指標談判",
  "封印 Release 卷軸",
  "用月光簽下 Commit",
  "召喚編譯精靈",
  "踏入 Stack Trace 迷宮",
  "向編譯器低語",
  "在事件迴圈縫時間",
] as const;

export function cloneDefaultDiscordWorkingIndicators(): string[] {
  return [...DEFAULT_DISCORD_WORKING_INDICATORS];
}
