export const DEFAULT_DISCORD_WORKING_INDICATORS = [
  "Alchemizing",
  "Aromatizing",
  "Assembling",
  "Beboppin'",
  "Bleeping",
  "Blooming",
  "Blooping",
  "Blossoming",
  "Blue Bossa-ing",
  "Bouqueting",
  "Brainstorming",
  "Bubbling",
  "Calibrating",
  "Carbonating",
  "Cascading",
  "Catalyzing",
  "Catching the groove",
  "Compiling",
  "Comping",
  "Composing",
  "Crystallizing",
  "Daydreaming",
  "Dazzling",
  "Decanting",
  "Deducing",
  "Defragmenting",
  "Distilling",
  "Dolphin Dancing",
  "Doodling",
  "Effervescing",
  "Embroidering",
  "Entering Monk's Dream",
  "Extrapolating",
  "Fascinating",
  "Fathoming",
  "Fermenting",
  "Fiddling",
  "Finding the pocket",
  "Finessing",
  "Fizzing",
  "Flatting the Fifth",
  "Flourishing",
  "Footprinting",
  "Formulating",
  "Freeloading",
  "Fully Altering the Dominant",
  "Gallivanting",
  "Gesticulating",
  "Getting Misty",
  "Glimmering",
  "Grooving",
  "Harmonizing",
  "Hitting the changes",
  "Humming",
  "Illuminating",
  "Improvising",
  "Infusing",
  "Investigating",
  "Jamming",
  "Juggling",
  "Lavenderizing",
  "Laying down tracks",
  "Materializing",
  "Meandering",
  "Nebulizing",
  "Noodling",
  "Oleo-ing",
  "Orchestrating",
  "Origami-ing",
  "Parsing",
  "Perambulating",
  "Perfuming",
  "Permutating",
  "Petalling",
  "Philosophizing",
  "Photosynthesizing",
  "Phytomerizing",
  "Ping-ponging",
  "Pinging",
  "Pirouetting",
  "Playing it cool like Miles",
  "Playing the head",
  "Plucking",
  "Polishing",
  "Pollinating",
  "Pruning",
  "Radiating",
  "Recalibrating",
  "Resonating",
  "Reverberating",
  "Riffing",
  "Rummaging",
  "Sashaying",
  "Scatting",
  "Scenting",
  "Scrutinizing",
  "Sequestering Days",
  "Sharping the Ninth",
  "Shedding Peggy's Blue Skylight",
  "Shedding Rhythm Changes",
  "Shimmering",
  "Sifting",
  "Soloing",
  "Sparkling",
  "Spiraling",
  "Sprinkling",
  "Sprouting",
  "Steeping",
  "Sublimating",
  "Substituting the Tritone",
  "Summertiming",
  "Swinging",
  "Synchronizing",
  "Syncopating",
  "Taking Giant Steps",
  "Taking it to the bridge",
  "Taking the A Train",
  "Tessellating",
  "Tiptoeing",
  "Trading fours",
  "Tuning",
  "Twiddling",
  "Twinkling",
  "Unscrambling",
  "Vamping",
  "Waltzing",
  "Weaving",
  "Whispering",
  "Whittling",
  "Whizzing",
  "Working the turnaround",
  "Zesting",
] as const;

export function cloneDefaultDiscordWorkingIndicators(): string[] {
  return [...DEFAULT_DISCORD_WORKING_INDICATORS];
}
