// Default bank of Discord streaming embed title indicators.
//
// Used when `surface.discord.workingIndicators` is omitted in `core-config.yaml`.
// To customize or keep things more serious, set `surface.discord.workingIndicators` explicitly.
export const DEFAULT_DISCORD_WORKING_INDICATORS = [
  // Original whimsical bank (upstream).
  "Alchemizing",
  "Aromatizing",
  "Assembling",
  "Bleeping",
  "Blooming",
  "Blooping",
  "Blossoming",
  "Bouqueting",
  "Brainstorming",
  "Bubbling",
  "Calibrating",
  "Carbonating",
  "Cascading",
  "Catalyzing",
  "Compiling",
  "Composing",
  "Crystallizing",
  "Daydreaming",
  "Dazzling",
  "Decanting",
  "Deducing",
  "Defragmenting",
  "Distilling",
  "Doodling",
  "Effervescing",
  "Embroidering",
  "Extrapolating",
  "Fascinating",
  "Fathoming",
  "Fermenting",
  "Fiddling",
  "Finessing",
  "Fizzing",
  "Flourishing",
  "Formulating",
  "Gallivanting",
  "Gesticulating",
  "Glimmering",
  "Harmonizing",
  "Humming",
  "Illuminating",
  "Infusing",
  "Investigating",
  "Juggling",
  "Lavenderizing",
  "Materializing",
  "Meandering",
  "Nebulizing",
  "Orchestrating",
  "Origami-ing",
  "Parsing",
  "Perambulating",
  "Perfuming",
  "Permutating",
  "Petalling",
  "Philosophizing",
  "Photosynthesizing",
  "Phytomerizing",
  "Ping-ponging",
  "Pinging",
  "Pirouetting",
  "Plucking",
  "Polishing",
  "Pollinating",
  "Pruning",
  "Radiating",
  "Recalibrating",
  "Resonating",
  "Reverberating",
  "Rummaging",
  "Sashaying",
  "Scenting",
  "Scrutinizing",
  "Shimmering",
  "Sifting",
  "Sparkling",
  "Spiraling",
  "Sprinkling",
  "Sprouting",
  "Steeping",
  "Sublimating",
  "Synchronizing",
  "Tessellating",
  "Tiptoeing",
  "Tuning",
  "Twiddling",
  "Twinkling",
  "Unscrambling",
  "Waltzing",
  "Weaving",
  "Whispering",
  "Whittling",
  "Whizzing",
  "Zesting",

  // Jazz spinner verbs (from chrismo's "claude-code-settings.json" gist):
  // https://gist.github.com/chrismo/b35434593e06fe4a2ea6eca13e4786da
  "Improvising",
  "Jamming",
  "Riffing",
  "Swinging",
  "Scatting",
  "Grooving",
  "Vamping",
  "Beboppin'",
  "Noodling",
  "Syncopating",
  "Comping",
  "Soloing",
  "Laying down tracks",
  "Finding the pocket",
  "Trading fours",
  "Taking it to the bridge",
  "Hitting the changes",
  "Playing the head",
  "Working the turnaround",
  "Catching the groove",
  "Substituting the Tritone",
  "Flatting the Fifth",
  "Sharping the Ninth",
  "Fully Altering the Dominant",
  "Taking the A Train",
  "Oleo-ing",
  "Shedding Rhythm Changes",
  "Taking Giant Steps",
  "Entering Monk's Dream",
  "Freeloading",
  "Playing it cool like Miles",
  "Sequestering Days",
  "Dolphin Dancing",
  "Blue Bossa-ing",
  "Getting Misty",
  "Summertiming",
  "Footprinting",
  "Shedding Peggy's Blue Skylight",

  // Extra: engineering-flavored memes (EN).
  "Appeasing the Linter",
  "Caching the Cosmos",
  "Chasing a Heisenbug",
  "Convincing DNS",
  "Deploying Hope",
  "Feeding the Garbage Collector",
  "Hydrating the Frontend",
  "Rebasing Reality",
  "Taming the Merge Dragon",
  "YAML Whispering",

  // Extra: engineering-flavored memes (ZH).
  "安撫 Linter 到點頭",
  "把 Deploy 當放天燈",
  "把 Log 當籤詩解",
  "把 Merge 衝突哄睡",
  "跟 DNS 講道理",
  "跟 TypeScript 喬條件",
  "在 Kubernetes 裡找出口",
  "對著 YAML 念咒",
  "替 Cache 點香拜拜",
  "追捕海森堡蟲",

  // Extra: chuuni / literary memes (EN).
  "Binding Bugs into Sigils",
  "Consulting the Prophecy Logs",
  "Carving Types into Stone",
  "Negotiating with the Void Pointer",
  "Sealing the Release Scroll",
  "Signing the Commit in Moonlight",
  "Summoning the Build Spirits",
  "Walking the Stack Trace Labyrinth",
  "Whispering to the Compiler",
  "Stitching Time in the Event Loop",

  // Extra: chuuni / literary memes (ZH).
  "把 Bug 鎖進符印",
  "翻閱預言般的 Logs",
  "以型別刻下誓約",
  "與虛無指標談判",
  "封印 Release 卷軸",
  "用月光簽下 Commit",
  "召喚編譯精靈",
  "踏入 Stack Trace 迷宮",
  "向編譯器低語",
  "在事件迴圈縫時間",
] as const;

export function cloneDefaultDiscordWorkingIndicators(): string[] {
  return [...DEFAULT_DISCORD_WORKING_INDICATORS];
}
