// Generated by scripts/generate-provider-option-shapes.ts. Do not edit.
export const MODEL_PROVIDER_OPTION_SHAPES = {
  anthropic: {
    kind: "object",
    properties: {
      anthropicBeta: {
        kind: "array",
        element: null,
      },
      cacheControl: {
        kind: "object",
        properties: {
          ttl: null,
          type: null,
        },
      },
      container: {
        kind: "object",
        properties: {
          id: null,
          skills: {
            kind: "array",
            element: {
              kind: "object",
              properties: {
                providerReference: null,
                skillId: null,
                type: null,
                version: null,
              },
            },
          },
        },
      },
      contextManagement: {
        kind: "object",
        properties: {
          edits: {
            kind: "array",
            element: {
              kind: "object",
              properties: {
                clearAtLeast: {
                  kind: "object",
                  properties: {
                    type: null,
                    value: null,
                  },
                },
                clearToolInputs: null,
                excludeTools: {
                  kind: "array",
                  element: null,
                },
                instructions: null,
                keep: {
                  kind: "object",
                  properties: {
                    type: null,
                    value: null,
                  },
                },
                pauseAfterCompaction: null,
                trigger: {
                  kind: "object",
                  properties: {
                    type: null,
                    value: null,
                  },
                },
                type: null,
              },
            },
          },
        },
      },
      disableParallelToolUse: null,
      effort: null,
      fallbacks: {
        kind: "array",
        element: {
          kind: "object",
          properties: {
            max_tokens: null,
            model: null,
            output_config: null,
            speed: null,
            thinking: null,
          },
        },
      },
      inferenceGeo: null,
      mcpServers: {
        kind: "array",
        element: {
          kind: "object",
          properties: {
            authorizationToken: null,
            name: null,
            toolConfiguration: {
              kind: "object",
              properties: {
                allowedTools: {
                  kind: "array",
                  element: null,
                },
                enabled: null,
              },
            },
            type: null,
            url: null,
          },
        },
      },
      metadata: {
        kind: "object",
        properties: {
          userId: null,
        },
      },
      sendReasoning: null,
      speed: null,
      structuredOutputMode: null,
      taskBudget: {
        kind: "object",
        properties: {
          remaining: null,
          total: null,
          type: null,
        },
      },
      thinking: {
        kind: "object",
        properties: {
          budgetTokens: null,
          display: null,
          type: null,
        },
      },
      toolStreaming: null,
    },
  },
  groq: {
    kind: "object",
    properties: {
      parallelToolCalls: null,
      reasoningEffort: null,
      reasoningFormat: null,
      serviceTier: null,
      strictJsonSchema: null,
      structuredOutputs: null,
      user: null,
    },
  },
  openai: {
    kind: "object",
    properties: {
      allowedTools: {
        kind: "object",
        properties: {
          mode: null,
          toolNames: {
            kind: "array",
            element: null,
          },
        },
      },
      contextManagement: {
        kind: "array",
        element: {
          kind: "object",
          properties: {
            compactThreshold: null,
            type: null,
          },
        },
      },
      conversation: null,
      forceReasoning: null,
      include: {
        kind: "array",
        element: null,
      },
      instructions: null,
      logprobs: null,
      maxToolCalls: null,
      metadata: null,
      parallelToolCalls: null,
      passThroughUnsupportedFiles: null,
      previousResponseId: null,
      promptCacheKey: null,
      promptCacheOptions: {
        kind: "object",
        properties: {
          mode: null,
          ttl: null,
        },
      },
      promptCacheRetention: null,
      reasoningContext: null,
      reasoningEffort: null,
      reasoningMode: null,
      reasoningSummary: null,
      safetyIdentifier: null,
      serviceTier: null,
      store: null,
      strictJsonSchema: null,
      systemMessageMode: null,
      textVerbosity: null,
      truncation: null,
      user: null,
    },
  },
  openaiCompatible: {
    kind: "object",
    properties: {
      reasoningEffort: null,
      strictJsonSchema: null,
      textVerbosity: null,
      user: null,
    },
  },
  xai: {
    kind: "object",
    properties: {
      include: {
        kind: "array",
        element: null,
      },
      logprobs: null,
      previousResponseId: null,
      reasoningEffort: null,
      reasoningSummary: null,
      store: null,
      topLogprobs: null,
    },
  },
} as const;
